server:
  port: 8085

jwt:
  secret: mZq3t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B&E)H+MbQe
  expirationMs: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth_service: DEBUG 

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Route for Authentication Service
        - id: auth-service-route
          # Route requests coming to the gateway at /auth/**
          predicates:
            - Path=/auth/**
          # Forward them to the auth-service base URL (running on port 8081)
          # The gateway automatically forwards the original path (/auth/login, /auth/token, etc.)
          uri: http://localhost:8082
          # No JWT filter applied here - handled by the global filter logic
        - id: document_service_route
          uri: http://localhost:8081 # Your Document Service
          predicates:
            - Path=/api/v1/categories/**, /api/v1/departments/**, /api/v1/documents/**
        
        - id: storage_service_route
          uri: http://localhost:8002 # Your Storage Service
          predicates:
            - Path=/api/v1/storage/**
          filters:
            - RewritePath=/api/v1/storage(?<segment>/?.*), $\{segment}

app:
  auth:
    header:
      names:
        user-id: X-User-Id        # Header name the Gateway will ADD for downstream services
        user-roles: X-User-Roles    # Header name the Gateway will ADD for downstream services
    excluded:
      # Full paths AS SEEN BY THE GATEWAY that should bypass JWT authentication
      # Example: if Auth service is at http://localhost:8090/auth/login
      # and your gateway route for auth is /api/v1/auth/**
      # then the excluded path is /api/v1/auth/login
      paths: /auth/login,/auth/register,/auth/signup,/auth/token 
      # Add other public paths like /swagger-ui.html, /v3/api-docs/** if needed


# Optional: Configure actuator endpoints (e.g., expose health)
# management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, gateway