version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: translation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123  # Change this!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Kafka + Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]

  # Spring Boot App
  springboot-app:
    build:
      context: ./springboot
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - postgres
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/translation_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    restart: unless-stopped

  # Python Translation Service
  python-translation:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python-translation
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      GEMINI_API_KEY: your_gemini_api_key_here  # Replace with your actual key
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SUPABASE_URL: your_supabase_url
      SUPABASE_KEY: your_supabase_key
    restart: unless-stopped

volumes:
  postgres_data: