server:
  port: 8082

spring:
  application:
    name: auth-service
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mZq3t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B&E)H+MbQe
  expirationMs: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth_service: DEBUG 