server:
  port: 8082

spring:
  application:
    name: auth-service

jwt:
  secret: mZq3t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B&E)H+MbQe
  expirationMs: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth_service: DEBUG 