# spring:
#   # H2 configuration for development
#   datasource:
#     url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#     username: sa
#     password: password
#     driver-class-name: org.h2.Driver
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
#       settings:
#         web-allow-others: false
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.H2Dialect
#         format_sql: true

# # Keep other settings from main config
# logging:
#   level:
#     root: INFO
#     com.example.document_service: DEBUG
#     org.springframework.security: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE
