version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3 
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - dms-network

  kafka:
    image: confluentinc/cp-kafka:7.5.3 
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092 
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - dms-network
      
  # Kafka setup service to create required topics
  kafka-setup:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-setup
    depends_on:
      - kafka
    restart: on-failure
    environment:
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties"
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' &&
        sleep 30 &&
        kafka-topics --bootstrap-server kafka:29092 --list &&
        echo 'Creating Kafka topics...' &&
        kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --topic document_events &&
        kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --topic document-translation-results &&
        echo 'Kafka topics created'
      "
    networks:
      - dms-network
      
  # --- Add MinIO Service ---
  minio:
    image: minio/minio:latest 
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin 
      MINIO_ROOT_PASSWORD: minioadmin 
    command: server /data --console-address ":9001" # Start server, expose console on 9001
    ports:
      - "9000:9000" 
      - "9001:9001" 
    volumes:
      - minio_data:/data 
    networks:
      - dms-network
    healthcheck: # Simple healthcheck
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 10s
        timeout: 5s
        retries: 3

  # MinIO setup service to create bucket
  minio-setup:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc config host add myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting for minio' && sleep 1; done;
      mc mb myminio/dms-documents --ignore-existing;
      mc anonymous set download myminio/dms-documents || echo 'Policy already set';
      exit 0;
      "
    networks:
      - dms-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: document_service
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - dms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8082
    networks:
      - dms-network

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
    depends_on:
      - auth-service
      - document-service
      - storage-service
    networks:
      - dms-network

  storage-service:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    container_name: storage-service
    restart: on-failure
    ports:
      - "8002:8002"
    environment:
      MINIO_ENDPOINT_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: dms-documents
      MINIO_USE_SSL: "false"
      PYTHONUNBUFFERED: "1"
    depends_on:
      minio-setup:
        condition: service_completed_successfully
    networks:
      - dms-network
    
  document-service:
    build:
      context: ./document-service
      dockerfile: Dockerfile
    container_name: document-service
    depends_on:
      - postgres
      - kafka
      - kafka-setup
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/document_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SERVER_PORT: 8080
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - dms-network

  translation-service:
    build:
      context: ./translation-service
      dockerfile: Dockerfile
    container_name: translation-service
    depends_on:
      - document-service
      - kafka
      - kafka-setup
    restart: always
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DOCUMENT_SERVICE_URL: http://document-service:8080
      GEMINI_API_KEY: AIzaSyAlSmyOjBZdoDUB0pI9_mRrMH26vq9gv5E
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge

volumes:
  minio_data:
  postgres_data:
  kafka_data:
  zookeeper_data:
  zookeeper_log: